@startuml
' Определение пользователей
actor "Пользователь" as User
actor "Специалист по установке" as Installer

' Определение системы
rectangle "Монолитное приложение Тёплый дом" as Soft

' Внешние устройства
rectangle "Датчики температуры" as Sensors
rectangle "Реле отопления" as Relays

' Взаимодействие пользователей
User->Soft : Управление отоплением\nПроверка температуры
Installer->Soft : Установка и настройка оборудования

' Взаимодействие системы с устройствами
Soft -> Sensors : Запрос текущей температуры
Soft -> Relays : Команда на включение/выключение отопления
@enduml